name: CI/CD Workflow for React App

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Sets up the Node.js environment
        with:
          node-version: '16'  # Defines the Node.js version

      - name: Install dependencies
        run: npm install  # Installs project dependencies

      - name: Run tests
        run: npm test -- --coverage  # Runs the tests with code coverage

      - name: Build project
        run: npm run build  # Builds the production version of the app

      - name: Deploy to GitHub Pages
        if: success()  # Only deploy if the previous steps were successful
        uses: JamesIves/github-pages-deploy-action@v4  # Action to deploy to GitHub Pages
        with:
          branch: gh-pages  # The target branch for GitHub Pages
          folder: build  # The folder to deploy (the output of `npm run build`)
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default GitHub token
