name: React CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can specify your version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test -- --coverage

      # Step 5: Build the React app
      - name: Build the app
        run: npm run build

      # Step 6: Deploy the app (optional, depending on your deployment method)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'  # Only deploy on main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
