name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to the latest version

      - name: Cache Docker layers
        uses: actions/cache@v3  # Updated to the latest version
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.run_id }}  # Changed key to avoid cache issues
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      - name: Run tests
        run: |
          docker run my-docker-image npm test

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag my-docker-image ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
